### ISSUE TITLE
Tried to call nil

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/openwig#164]
```
What cartridge are you playing?
http://www.wherigo.com/cartridge/download.aspx?CGUID=b6a00fcb-0a82-4399-b1e9-dcd
d617d61ec

What is your phone/PDA manufacturer and model? What GPS are you using?
Debian Linux. No GPS chosen.

What steps will reproduce the problem?
1. Start
2. Change coordinates, Save, Exit.
3. Restart, resume.

What is the expected output? What happens instead?
Error Dialog.

If you see an error screen, please type its contents here:
Creating engine...
Creating state...
Building javafunc map...
Loading stdlib...calling...
Registering WIG libs...
Building event queue...
Restoring saved state...Starting game...
java.lang.RuntimeException: Tried to call nil
    at se.krka.kahlua.stdlib.BaseLib.fail(BaseLib.java:390)
    at se.krka.kahlua.stdlib.BaseLib.luaAssert(BaseLib.java:385)
    at se.krka.kahlua.vm.LuaState.luaMainloop(LuaState.java:666)
    at se.krka.kahlua.vm.LuaState.call(LuaState.java:217)
    at se.krka.kahlua.vm.LuaState.call(LuaState.java:1135)
    at cz.matejcik.openwig.EventTable.callEvent(EventTable.java:108)
    at cz.matejcik.openwig.Engine.run(Engine.java:212)
    at java.lang.Thread.run(Thread.java:662)
at @E:/webtempfiles/648bfc34-3465-4adc-b73a-1aa8ce1cd648/_cartridge-new.enc:12
at @E:/webtempfiles/648bfc34-3465-4adc-b73a-1aa8ce1cd648/_cartridge-new.enc:571

java.lang.RuntimeException: Tried to call nil
    at se.krka.kahlua.stdlib.BaseLib.fail(BaseLib.java:390)
    at se.krka.kahlua.stdlib.BaseLib.luaAssert(BaseLib.java:385)
    at se.krka.kahlua.vm.LuaState.luaMainloop(LuaState.java:666)
    at se.krka.kahlua.vm.LuaState.call(LuaState.java:217)
    at se.krka.kahlua.vm.LuaState.call(LuaState.java:1135)
    at cz.matejcik.openwig.EventTable.callEvent(EventTable.java:108)
    at cz.matejcik.openwig.Engine$2.run(Engine.java:281)
    at util.BackgroundRunner.run(BackgroundRunner.java:55)
at @E:/webtempfiles/648bfc34-3465-4adc-b73a-1aa8ce1cd648/_cartridge-new.enc:12
at @E:/webtempfiles/648bfc34-3465-4adc-b73a-1aa8ce1cd648/_cartridge-new.enc:571
at @E:/webtempfiles/648bfc34-3465-4adc-b73a-1aa8ce1cd648/_cartridge-new.enc:12
at @E:/webtempfiles/648bfc34-3465-4adc-b73a-1aa8ce1cd648/_cartridge-new.enc:764


What version are you using?
DesktopWIG-0.1-experimental

Please provide any additional information below.

```

Original issue reported on code.google.com by `cej...@gmail.com` on 16 Nov 2011 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
hello,
thanks for the report and sorry about several months delay.
a new version of DesktopWIG was released today that does not have this error. 
please try it and report back if you have more problems
```

Original comment by `matej...@gmail.com` on 11 Mar 2012 at 6:14
- Changed state: **Fixed**
