### ISSUE TITLE
java.lang.RuntimeException: bad argument #1to 'byte' (string expected, got no value)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/openwig#167]
```
What cartridge are you playing?
Whereigoium

What is your phone/PDA manufacturer and model? What GPS are you using?
DesktopWIG

What steps will reproduce the problem?
1. Start


What is the expected output? What happens instead?


If you see an error screen, please type its contents here:

Starting game...
java.lang.RuntimeException: bad argument #1to 'byte' (string expected, got no 
value)
        at se.krka.kahlua.stdlib.BaseLib.getArg(BaseLib.java:424)
        at se.krka.kahlua.stdlib.StringLib.getStringArg(StringLib.java:663)
        at se.krka.kahlua.stdlib.StringLib.stringByte(StringLib.java:700)
        at se.krka.kahlua.stdlib.StringLib.call(StringLib.java:107)
        at se.krka.kahlua.vm.LuaState.callJava(LuaState.java:233)
        at se.krka.kahlua.vm.LuaState.luaMainloop(LuaState.java:692)
        at se.krka.kahlua.vm.LuaState.call(LuaState.java:217)
        at se.krka.kahlua.vm.LuaState.call(LuaState.java:1135)
        at cz.matejcik.openwig.EventTable.callEvent(EventTable.java:108)
        at cz.matejcik.openwig.Engine.run(Engine.java:212)
        at java.lang.Thread.run(Unknown Source)
at byteat 
@E:/webtempfiles/0ae3e92d-65ff-4c8f-83f8-0b1583e18923/Wherigoium-new.enc:158
at @E:/webtempfiles/0ae3e92d-65ff-4c8f-83f8-0b1583e18923/Wherigoium-new.enc:377

What version are you using?


Please provide any additional information below.

```

Original issue reported on code.google.com by `rickr...@gmail.com` on 25 Dec 2011 at 10:28

**Comment by GoogleCodeExporter** [comment]
```
hello, thanks for your report.
this is a known bug that is already fixed in the development version, and will 
be included in next release.
(however, i can't say when that next release will happen :( )
```

Original comment by `matej...@gmail.com` on 9 Jan 2012 at 5:16
- Changed state: **Waiting**
